### ISSUE TITLE
optimal_values loss matrix error

### ISSUE THREAD

**Issue by nsryan2** [arfc/cairo#66]
If, in the unlikely event, someone uses a loss matrix that has two zeros in it, the function optimal_values in the tools module outputs a type error. This behavior seems, of the numbers I tested, to be limited to loss matrices with two or more zeros. 

The error arises because the intermediary index_min contains, when there are two or more zeros in the loss matrix, arrays with more than one element. This makes it impossible for the subsequent x_optimal and y_optimal to grab an entry as an integer.

One possible solution is to add an additional reference in the definitions of x or y_optimal such that they say
`x_optimal = xset[int(index_min[0][0])]`
This way, even if the arrays contain one entry, it will still be grabbed. So long as the number of times the optimal value comes up doesn't matter, this should work, but I'm not sure if that's important or not.

**Comment by samgdotson** [comment]
I wrote this big long explanation about how to choose the best set if there are duplicates, but I don't think that's correct behavior, actually. It's not just unlikely to happen, it will *never* happen. They might be close, but they won't ever be the same unless we round the loss values (which we don't do). 
In fact, if we do get two or more identical values, that's a good sign there is something wrong elsewhere in the code (this happened to me when I failed to loop over parameters properly). 

So, I'm closing this issue because
1. It's non-trivial to choose ideal parameter sets in these cases (many many edges and corners to test)
2. It will never happen during correct execution
3. It's not the behavior we want anyway.
